# Generated by Django 5.2.4 on 2025-07-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
